# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '04_信号与槽.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.pushButton_closeWin = QtWidgets.QPushButton(Form)
        self.pushButton_closeWin.setGeometry(QtCore.QRect(180, 150, 75, 23))
        self.pushButton_closeWin.setObjectName("pushButton_closeWin")

        self.retranslateUi(Form)
        self.pushButton_closeWin.clicked.connect(Form.close)
        # 信号与槽的高级应用 可有可无
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_closeWin.setText(_translate("Form", "关闭"))
