# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(287, 175)
        self.textEdit = QtWidgets.QTextEdit(Form1)
        self.textEdit.setGeometry(QtCore.QRect(60, 30, 104, 71))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Form"))
