# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(801, 588)
        self.textEdit = QtWidgets.QTextEdit(Form2)
        self.textEdit.setGeometry(QtCore.QRect(140, 100, 104, 71))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form2)
        self.label.setGeometry(QtCore.QRect(150, 50, 54, 12))
        self.label.setObjectName("label")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
        self.label.setText(_translate("Form2", "TextLabel"))
