# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_test(object):
    def setupUi(self, Login_test):
        Login_test.setObjectName("Login_test")
        Login_test.setEnabled(True)
        Login_test.resize(479, 258)
        self.widget = QtWidgets.QWidget(Login_test)
        self.widget.setGeometry(QtCore.QRect(230, 220, 160, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login_Button = QtWidgets.QPushButton(self.widget)
        self.login_Button.setObjectName("login_Button")
        self.horizontalLayout_3.addWidget(self.login_Button)
        self.cancel_Button = QtWidgets.QPushButton(self.widget)
        self.cancel_Button.setObjectName("cancel_Button")
        self.horizontalLayout_3.addWidget(self.cancel_Button)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.user_textBrowser = QtWidgets.QTextBrowser(Login_test)
        self.user_textBrowser.setGeometry(QtCore.QRect(199, 12, 256, 192))
        self.user_textBrowser.setObjectName("user_textBrowser")
        self.widget1 = QtWidgets.QWidget(Login_test)
        self.widget1.setGeometry(QtCore.QRect(12, 12, 181, 191))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_name_label = QtWidgets.QLabel(self.widget1)
        self.user_name_label.setObjectName("user_name_label")
        self.verticalLayout.addWidget(self.user_name_label)
        self.pwd_label = QtWidgets.QLabel(self.widget1)
        self.pwd_label.setObjectName("pwd_label")
        self.verticalLayout.addWidget(self.pwd_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.user_name_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.user_name_lineEdit.setObjectName("user_name_lineEdit")
        self.verticalLayout_2.addWidget(self.user_name_lineEdit)
        self.pwd_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.pwd_lineEdit.setObjectName("pwd_lineEdit")
        self.verticalLayout_2.addWidget(self.pwd_lineEdit)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Login_test)
        QtCore.QMetaObject.connectSlotsByName(Login_test)

    def retranslateUi(self, Login_test):
        _translate = QtCore.QCoreApplication.translate
        Login_test.setWindowTitle(_translate("Login_test", "Form"))
        self.login_Button.setText(_translate("Login_test", "登录"))
        self.cancel_Button.setText(_translate("Login_test", "退出"))
        self.user_name_label.setText(_translate("Login_test", "用户名"))
        self.pwd_label.setText(_translate("Login_test", "密码"))
